name: opencv-cuda

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - opencv
  pull_request:
    branches:
      - 'master'
    paths:
      - opencv  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/zoneminder.machine.learning/opencv-base
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: opencv
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}